export const UI_STRINGS = {
  zh: {
    title: '词汇大师',
    subtitle: 'YCT 词汇分类与敏捷识别挑战',
    singlePlayer: '单人模式：分类竞技',
    twoPlayer: '双人模式：找不同',
    introduction: '游戏说明',
    selectLevel: '选择级别',
    selectLesson: '选择课时',
    previewTitle: '词汇准备预览',
    previewSubtitle: '预览本关词汇所对应的分类标签，打好基础开始挑战吧！',
    startChallenge: '开始挑战',
    back: '返回',
    score: '得分',
    accuracy: '准确率',
    time: '时间',
    lives: '生命值',
    combo: '连击',
    gameOver: '游戏结束',
    pause: '暂停',
    resume: '继续',
    restart: '重新开始',
    quit: '退出',
    settlementTitle: '挑战结算报告',
    errorAnalysis: '错题详细分析汇总',
    word: '词汇',
    pinyin: '拼音',
    translation: '翻译',
    correctCategory: '正确分类',
    yourChoice: '你的选择',
    playAgain: '再玩一次',
    nextLevel: '下一关',
    mainMenu: '回到主页',
    itemTitle: '极速道具',
    frozenActive: '气泡被冰冻减速中！',
    shrinkActive: '词块尺寸已缩小！',
    hintActive: '提示卡常询高亮中！',
    howToPlay1: '单人模式：滑动或拖拽不断掉落的汉字气泡到正确的“分类篮”中，正确获得10分，错误或漏选将扣分并流失生命。可以使用游戏内冰冻、提示道具！',
    howToPlay2: '双人模式（找不同）：左右/上下分屏对抗。屏幕中间随机生成4-6个汉字气泡，其中有1-2个属于其他维度的“干扰项”（异类）。最快点击/切割出异类的玩家即可加分！失误会扣分，抢答吧！',
    howToPlayBonus: '使用双人竞技时：左侧玩家和右侧玩家可以分别触屏或在电脑端键盘抢切。抢先切割，看谁的速度更快、反应最准！',
    categoryLabel: '词汇分类',
    reviewAll: '第12课：全书总复习',
    styleSelect: '选择风格',
    themeDark: '深空流光 🌌',
    themeCartoon: '活泼卡通 🧸',
    themeClassic: '古风书香 🎋'
  },
  en: {
    title: 'Lexical Master',
    subtitle: 'YCT Vocabulary Categorization & Speed Challenge',
    singlePlayer: 'Single Player: Classify Arena',
    twoPlayer: 'Versus Player: Spotlight Odd-one-out',
    introduction: 'Instruction Guide',
    selectLevel: 'Select YCT Level',
    selectLesson: 'Select Lesson Range',
    previewTitle: 'Vocabulary Preview & Study',
    previewSubtitle: 'Review terms and their correct categories. Memorize them before starting!',
    startChallenge: 'Start Game',
    back: 'Back',
    score: 'Score',
    accuracy: 'Accuracy',
    time: 'Time Left',
    lives: 'HP Hearts',
    combo: 'Combos',
    gameOver: 'Game Over',
    pause: 'Pause',
    resume: 'Resume',
    restart: 'Restart',
    quit: 'Quit',
    settlementTitle: 'Final Report Card',
    errorAnalysis: 'Detailed Error Review & Analysis',
    word: 'Character',
    pinyin: 'Pinyin',
    translation: 'Meaning',
    correctCategory: 'Correct Category',
    yourChoice: 'Your Choice',
    playAgain: 'Play Again',
    nextLevel: 'Next Stage',
    mainMenu: 'Home Menu',
    itemTitle: 'Arcade Powers',
    frozenActive: 'Freeze Gun: Bubbles slowed!',
    shrinkActive: 'Shrink Lens: Bubble sizes smaller!',
    hintActive: 'Hint Card: Helpers highlighted!',
    howToPlay1: 'Single Player Mode: Drag or swipe descending Chinese vocabulary bubbles into the correct corresponding themed category buckets. Correct adds 10 pts, mistakes or letting obstacles drop lose hearts and deduct 5 pts.',
    howToPlay2: 'Two Player Split-screen Mode: Side-by-side splits (top-bottom on mobile). Instant randomized bubbles show up. 1 or 2 are "Odd-ones-out" from a different category. Swiftly slash the imposters first to score points!',
    howToPlayBonus: 'Versus rules: Tap / swipe on-screen bubbles. Fastest accurate slash wins the round. Ready your fingers!',
    categoryLabel: 'Category tag',
    reviewAll: 'Lesson 12: Level Cumulative Review',
    styleSelect: 'Select Style',
    themeDark: 'Cosmic Slate 🌌',
    themeCartoon: 'Pop Cartoon 🧸',
    themeClassic: 'Classic Ink 🎋'
  },
  mn: {
    title: 'Үгийн Магистр',
    subtitle: 'YCT Үгсийн ангилал ба хурд сорих тэмцээн',
    singlePlayer: 'Ганцаарчилсан: Ангилах тэмцээн',
    twoPlayer: 'Хоёр тоглогч: Өөрийгөө сорих',
    introduction: 'Тоглоомын заавар',
    selectLevel: 'YCT Түвшин Сонгох',
    selectLesson: 'Хичээл Сонгох',
    previewTitle: 'Үгсийн бэлтгэл толь',
    previewSubtitle: 'Тоглоом эхлэхээс өмнө үгсийн ангиллыг харж тогтоож аваарай!',
    startChallenge: 'Тоглож эхлэх',
    back: 'Буцах',
    score: 'Оноо',
    accuracy: 'Нарийвчлал',
    time: 'Цаг',
    lives: 'Амь',
    combo: 'Амжилт',
    gameOver: 'Тоглоом дууслаа',
    pause: 'Түр зогсоох',
    resume: 'Үргэлжлүүлэх',
    restart: 'Дахин эхлүүлэх',
    quit: 'Гарах',
    settlementTitle: 'Үр дүнгийн тайлан',
    errorAnalysis: 'Алдаа ба дүн шинжилгээ',
    word: 'Ханз',
    pinyin: 'Пиньинь',
    translation: 'Орчуулга',
    correctCategory: 'Зөв ангилал',
    yourChoice: 'Таны сонголт',
    playAgain: 'Дахин тоглох',
    nextLevel: 'Дараагийн даваа',
    mainMenu: 'Нүүр хуудас',
    itemTitle: 'Тусгай хэрэгслүүд',
    frozenActive: 'Мөсөн буу идэвхтэй байна!',
    shrinkActive: 'Хэмжээ жижигрүүлсэн байна!',
    hintActive: 'Идэвхтэй зөвлөгөө карт!',
    howToPlay1: 'Ганцаарчилсан горим: Дээрээс унах ханзтай бөмбөлгүүдийг зөв Сагс руу чирч хийнэ. Зөв бол +10 оноо, алдвал зүрх хасагдаж -5 оноо болно.',
    howToPlay2: 'Хоёр тоглогчийн горим: Дэлгэц хоёр хуваагдана. Санамсаргүй 4-6 үг дундаас өөр ангиллын "илүүц" үгийг ож хамгийн түрүүнд дарж хайчилна. Түрүүлж зөв дарсан нь оноо авна.',
    howToPlayBonus: 'Даваанд: Тоглогчид дэлгэцэнд зэрэг хүрч тоглох боломжтой. Хэн хурдан бөгөөд зөв хариулсан нь оноо авна!',
    categoryLabel: 'Үгсийн ангилал',
    reviewAll: '12-р хичээл: Багц давталт',
    styleSelect: 'Загвар Сонгох',
    themeDark: 'Сүүн Сар 🌌',
    themeCartoon: 'Хүүхэлдэйн 🧸',
    themeClassic: 'Сонгодог Бэхийн 🎋'
  }
};
